volumes:
  postgres-data:

services:
  postgres:
    image: postgres:alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
      POSTGRES_DB: "tenso"
    restart: always
    ports:
      - "5432:5432"
